# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_puppet = <<-PUPPET
sudo apt-get install -y puppet
PUPPET

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote = true
  end

  config.vm.define :balancer do |balancer|
    balancer.vm.box = "bento/ubuntu-20.04"
    balancer.vm.network :private_network, ip: "192.168.2.10"
    balancer.vm.hostname = "balancer"
    balancer.vm.provision "shell", path: "./aprovisionamiento/balancer.sh"
  end

  config.vm.define :vm2 do |vm2|
    vm2.vm.box = "bento/ubuntu-20.04"
    vm2.vm.network :private_network, ip: "192.168.2.11"
    vm2.vm.hostname = "vm2"
    vm2.vm.provision "shell", path: "./aprovisionamiento/vm2.sh"
  end

  config.vm.define :vm3 do |vm3|
    vm3.vm.box = "bento/ubuntu-20.04"
    vm3.vm.network :private_network, ip: "192.168.2.12"
    vm3.vm.hostname = "vm3"
    vm3.vm.provision "shell", path: "./aprovisionamiento/vm3.sh"
  end

end